### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by mysliwy112** [Dove6/dePIKczer#2] opened 2019-04-18 18:23 UTC
Some images responsible for collision are unreadable after conversion.

Example:
\Reksio i Kretes w Akcji\dane\game\przygoda\piraci\wall0.img

**Comment by Dove6** [comment] 2019-04-20 11:17
Fixed with [most recent commit](https://github.com/Dove6/dePIKczer/commit/8b7abf70e7f5bcb6b79611888b6da22136a6ce39). Output doesn't exactly represent input yet, but at least the output file can be opened :P

**Closed as completed by Dove6** 2019-04-20 11:17 UTC
Labels: bug

**Comment by Dove6** [comment] 2019-04-20 12:59
[By now](https://github.com/Dove6/dePIKczer/commit/cb606c46fac43043d34b2766de45f7545f4ddf71) the problem is completely solved, with newly included RGB pixel format conversion.
